api_product_workshop_new:
    path:     /workshops
    defaults: { _controller: ProductBundle:Api/Workshop:new }
    methods: POST

api_product_workshop_show:
    path:     /workshops/{id}
    defaults: { _controller: ProductBundle:Api/Workshop:show }
    methods: GET

api_product_workshop_list:
    path:     /workshops
    defaults: { _controller: ProductBundle:Api/Workshop:list }
    methods: GET

api_product_workshop_update:
    path:     /workshops/{id}
    defaults: { _controller: ProductBundle:Api/Workshop:update }
    methods: [PUT, PATCH]

api_product_workshop_delete:
    path:     /workshops/{id}
    defaults: { _controller: ProductBundle:Api/Workshop:delete }
    methods: DELETE