fos_user:
    resource: "@UserBundle/Resources/config/routing/fosuser.yml"

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /order

prestation:
    resource: "@PrestationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /


